name: Upload Files to Server

on:
  push:
    branches:
      - master
    paths:
      - docs/zebra-axios-docs/**
      - example/**

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Docs dependencies
        run: npm install
        working-directory: docs/zebra-axios-docs

      - name: Build Site
        run: npm run build
        working-directory: docs/zebra-axios-docs

      - name: Upload File via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'docs/zebra-axios-docs/.output,docs/zebra-axios-docs/Dockerfile'
          target: '/www/wwwroot/zebraui-axios-docs/'
          rm: true

      - name: ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          last_ssh: |
            cd /www/wwwroot/zebraui-axios-docs/docs/zebra-axios-docs
            docker stop zebra-axios-docs-docker
            docker rm -f zebra-axios-docs-docker
            docker build -t zebra-axios-docs-docker .
            docker run --name zebra-axios-docs-docker -d -p 3021:3021 -e PORT=3021 zebra-axios-docs-docker
